#!/bin/bash
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

sudo apt install vlc vlc-plugin-notify
sudo apt install steam
sudo apt install freeglut3 freeglut3-dev
sudo apt install ubuntu-restricted-extras
sudo apt install libavcodec-extra
sudo apt install curl

echo "Enter your email (for git):"
read email
echo "Enter your name (for git):"
read name
git config --global user.email "$email"
git config --global user.name "$name"
git config --global push.default simple

pushd ~/
git clone git@github.com:linuxfreak003/homework.git
git clone git@github.com:linuxfreak003/configs.git
git clone git@github.com:linuxfreak003/mandelbrot.git
popd

mkdir ~/setup
pushd ~/setup
git clone git@github.com:linuxfreak003/vimconfigs.git
git clone git@github.com:linuxfreak003/ocamlsetup.git
git clone git@github.com:linuxfreak003/golangsetup.git
popd
