#!/bin/bash

sudo add-apt-repository ppa:papirus/papirus
sudo add-apt-repository ppa:noobslab/themes

sudo apt update && sudo apt install papirus-icon-theme faience-theme

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /' >> /etc/apt/sources.list.d/arc-theme.list"
wget http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key
sudo apt-key add - < Release.key
sudo apt-get update && sudo apt-get install arc-theme
